M48
; DRILL file {KiCad 6.0.10-86aedd382b~118~ubuntu20.04.1} date Sat 07 Jan 2023 06:02:49 PM PST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-01-07T18:02:49-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.10-86aedd382b~118~ubuntu20.04.1
; #@! TF.FileFunction,MixedPlating,1,2
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
%
G90
G05
T1
X4.5768Y-2.9409
T0
M30
